---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sysdig
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.sysdig.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig-agent
spec:
  chart:
    spec:
      chart: sysdig-deploy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sysdig
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: sysdig-agent
  targetNamespace: sysdig-agent
  values:
    admissionController:
      enabled: true
      scanner:
        enabled: false
    agent:
      monitor:
        enabled: false
    global:
      clusterConfig:
        name: lima-k8s
      kspm:
        deploy: true
      sysdig:
        accessKey: MY_ACCESS_KEY
        region: us2
        secureAPIToken: MY_API_TOKEN
        tags:
          hypervisor: qemu
          location: local
          os: macos
          platform: arm64
    nodeAnalyzer:
      nodeAnalyzer:
        benchmarkRunner:
          deploy: false
        hostScanner:
          deploy: true
          scanOnStart: true
        runtimeScanner:
          settings:
            eveEnabled: true
      secure:
        vulnerabilityManagement:
          newEngineOnly: true
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: apps/v1
            kind: DaemonSet
            metadata:
              name: sysdig-agent-node-analyzer
              namespace: sysdig-agent
              annotations:
                vault.hashicorp.com/agent-inject-secret-foo: database/roles/app
                vault.hashicorp.com/agent-inject-secret-bar: consul/creds/app
                vault.hashicorp.com/role: 'app'